### ISSUE TITLE
Exists 함수에서 에러 처리 필요

### ISSUE THREAD

**Issue by kybin** [jyub86/imageConverter#1]
Exists의 Stat 호출에서 에러가 났을때 true를 리턴하게 돼요.

현재 Exists함수가 bool만 반환하게 되어서 에러시 리턴값을 정의하기가 애매한데
(bool, error)를 반환하게 하는 것도 좋은 방법일 것 같아요.

현재 main 패키지 안이니까 log.Fatal을 호출하는 것도 한가지 방법이구요.

**Comment by jyub86** [comment]
아하 감사합니다!  리뷰 반영하여 수정하였습니다!!!
